#!/bin/bash

# command: ${0}
# description: Simple shell script to check the lustre group quota limits.
#              Send an email when the threshold is exceeded.


VERSION=0.5
FILESYSTEM="/home"
PATH=$PATH:/usr/bin


if [ -n "${DEBUG}" ] && [ "${DEBUG}" == "1" ]; then
    set -x
fi


msg() {
    cat <<__EOF__
Caro ${name} ${surname},

questa email automatica le e' stata inviata per notificarle il superamento
della soglia di controllo configurata pari al ${threshold}%.

Di seguito alcuni dati:

Occupazione: ${number_of_files%\*}KB
Limiti:      ${hard_limit}KB

Grazie e buona giornata,
${0}

__EOF__
}


sendmail() {
    msg | mail -s "Lustre quota exeeding" ${email}
}


usage() {
    cat <<__EOF__
Simple shell script to check the lustre group quota limits.
Send an email when the threshold is exceeded.

Usage:
   quotachek.sh <-t|--threshold> <-e|--email> <group>

Options:
    -t|--threshold  Threshold to monitor (Percentage value e.g. 80%)
    -e|--email      Email address to notify 

Argument:
    group           Group to check 

Test:
    Specifing the type of test in the environment variable TEST.
    TEST can assume one values of soft, hard or veryhard.

DEBUG:
    Set the environment variable DEBUG with the value 1.

Examples:
    $ ${0} -t 80% -e hello@world.it matteo
    $ TEST=soft ${0} -t 30% -e hello@world.it matteo
    $ DEBUG=1 ${0} -t 50% -e hello@world.it matteo

__EOF__
}


command() {
    lfs quota -qg ${group} ${FILESYSTEM}
}


test_command() {
    if [ "$TEST" == "soft" ]; then
        echo "${FILESYSTEM}   10232   10240   20480       -      24*      5      10       -"
    elif [ "$TEST" == "hard" ]; then
    	echo "${FILESYSTEM}   20532*  10240   20480       -      34*      5      10       -"
    elif [ "$TEST" == "veryhard" ]; then
    	echo "${FILESYSTEM}   30772*  10240   20480       -      44*      5      10       -"
    fi
}


while [ ${#} -gt 0 ]
do
    arg=${1}
    shift
    case "${arg}" in
        -t|--threshold)
            threshold=${1%\%}
            shift
        ;;
        -e|--email)
            email=${1}
            shift
        ;;
        -h|--help)
            usage
            exit 0
        ;;
        -v|--version)
            echo "${VERSION}"
            exit 0
        ;;
        -*)
            usage "You have specified an invalid option: ${arg}"
            exit 1
        ;;
        *)
            group=${arg}
     esac
done


if [ -z "${group}" -o -z "${email}" -o -z "${threshold}" ]; then
    usage
    exit 0
fi


if [ -n "$TEST" ];then
    declare -a quota=(`test_command`)
else
    declare -a quota=(`command`)
fi


declare -a userdata=(`finger $USER`)
name=${userdata[3]}
surname=${userdata[4]}
number_of_files=${quota[1]}
soft_limit=${quota[2]}
hard_limit=${quota[3]}
grace=${quota[4]}
number_of_inode=${quota[5]}
soft_limit_inode=${quota[6]}
hard_limit_inode=${quota[7]}
grace_inode=${quota[8]}
hard_limit_threshold=$(( ${hard_limit}*${threshold}/100 ))


# Send an email if exeeding the threshold
if [ "${number_of_files%\*}" -gt "${hard_limit_threshold}" ]; then
    sendmail
fi

exit 0

# vim: set ts=8 sw=4 sts=4 tw=79 ff=unix ft=sh et ai :
